package com.xgen.mongot.index.lucene;

import static com.xgen.mongot.util.Check.checkState;
import static java.lang.String.format;

import com.google.errorprone.annotations.Var;
import com.xgen.mongot.index.FacetBucket;
import com.xgen.mongot.index.FacetInfo;
import com.xgen.mongot.index.MetaResults;
import com.xgen.mongot.index.definition.FieldTypeDefinition;
import com.xgen.mongot.index.lucene.explain.explainers.FacetFeatureExplainer;
import com.xgen.mongot.index.lucene.explain.timing.ExplainTimings;
import com.xgen.mongot.index.lucene.facet.TokenFacetsStateCache;
import com.xgen.mongot.index.lucene.facet.TokenSsdvFacetState;
import com.xgen.mongot.index.lucene.field.FieldName;
import com.xgen.mongot.index.lucene.searcher.LuceneIndexSearcher;
import com.xgen.mongot.index.query.CollectorQuery;
import com.xgen.mongot.index.query.InvalidQueryException;
import com.xgen.mongot.index.query.ReturnScope;
import com.xgen.mongot.index.query.collectors.FacetCollector;
import com.xgen.mongot.index.query.collectors.FacetDefinition;
import com.xgen.mongot.index.query.counts.Count;
import com.xgen.mongot.util.CheckedStream;
import com.xgen.mongot.util.CollectionUtils;
import com.xgen.mongot.util.FieldPath;
import com.xgen.mongot.util.concurrent.NamedExecutorService;
import com.xgen.mongot.util.timers.InvocationCountingTimer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.apache.lucene.facet.DrillSideways.DrillSidewaysResult;
import org.apache.lucene.facet.FacetResult;
import org.apache.lucene.facet.Facets;
import org.apache.lucene.facet.FacetsCollector;
import org.apache.lucene.facet.sortedset.ConcurrentSortedSetDocValuesFacetCounts;
import org.apache.lucene.facet.sortedset.SortedSetDocValuesFacetCounts;
import org.apache.lucene.index.FieldInfo;
import org.apache.lucene.index.FieldInfos;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.index.MultiTerms;
import org.apache.lucene.index.Terms;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.search.TotalHits;
import org.bson.BsonString;
import com.xgen.mongot.index.TermStatsInfo;
import com.xgen.mongot.index.query.TermStatsRequest;

/**
 * Holds the logic for building {@link MetaResults} from the artifacts generated by a lucene search.
 */
class LuceneMetaResultsBuilder {

  private final LuceneFacetContext facetContext;
  private final Optional<NamedExecutorService> concurrentSearchExecutor;

  public LuceneMetaResultsBuilder(
      LuceneFacetContext facetContext, Optional<NamedExecutorService> concurrentSearchExecutor) {
    this.facetContext = facetContext;
    this.concurrentSearchExecutor = concurrentSearchExecutor;
  }

  public MetaResults getCountMetaResults(TopDocs topDocs, Count.Type countType) {
    return new MetaResults(LuceneFacetResultUtil.getCount(topDocs.totalHits.value, countType));
  }

  /**
   * Builds MetaResults with count and optionally term statistics.
   *
   * @param searcherReference Reference to the Lucene index searcher
   * @param topDocs The top documents from the search
   * @param countType The type of count to return
   * @param termStatsRequest Optional request for term statistics
   * @return MetaResults with count and optional term statistics
   */
  public MetaResults getCountAndTermStatsMetaResults(
      LuceneIndexSearcherReference searcherReference,
      TopDocs topDocs,
      Count.Type countType,
      Optional<TermStatsRequest> termStatsRequest)
      throws IOException {
    Optional<Map<String, TermStatsInfo>> termStats = collectTermStats(searcherReference, termStatsRequest);
    return new MetaResults(
        LuceneFacetResultUtil.getCount(topDocs.totalHits.value, countType),
        Optional.empty(),
        termStats);
  }

  public MetaResults buildFacetMetaResults(
      LuceneIndexSearcherReference searcherReference,
      TopDocs topDocs,
      FacetsCollector collector,
      CollectorQuery collectorQuery,
      boolean concurrentSearch)
      throws IOException, InterruptedException, InvalidQueryException {

    // Ensure that we have an exact count.
    checkState(
        topDocs.totalHits.relation == TotalHits.Relation.EQUAL_TO,
        "FacetsCollector did not provide an exact count");
    var totalCount = topDocs.totalHits.value;
    var returnScopePath = collectorQuery.returnScope().map(ReturnScope::path);
    return switch (collectorQuery.collector()) {
      case FacetCollector facetCollector -> {
        Map<FacetDefinition.Type, Map<String, FacetDefinition>> typeToFacetToDefinition =
            facetCollector.getFacetDefinitionsByType();

        Map<String, FacetInfo> facets =
            Stream.of(
                    getStringFacetResult(
                        searcherReference,
                        typeToFacetToDefinition.get(FacetDefinition.Type.STRING),
                        collector,
                        returnScopePath,
                        concurrentSearch),
                    getBoundaryFacetResults(
                        typeToFacetToDefinition.get(FacetDefinition.Type.NUMBER),
                        collector,
                        this.facetContext,
                        totalCount,
                        returnScopePath),
                    getBoundaryFacetResults(
                        typeToFacetToDefinition.get(FacetDefinition.Type.DATE),
                        collector,
                        this.facetContext,
                        totalCount,
                        returnScopePath))
                .flatMap(map -> map.entrySet().stream())
                .collect(CollectionUtils.toMapUnsafe(Map.Entry::getKey, Map.Entry::getValue));

        Optional<Map<String, TermStatsInfo>> termStats = 
            collectTermStats(searcherReference, collectorQuery.termStats());

        yield new MetaResults(
            LuceneFacetResultUtil.getCount(topDocs.totalHits.value, collectorQuery.count().type()),
            Optional.of(facets),
            termStats);
      }
    };
  }

  public MetaResults buildDrillSidewaysFacetMetaResults(
      LuceneIndexSearcherReference searcherReference,
      TopDocs topDocs,
      CollectorQuery collectorQuery,
      Function<String, Optional<DrillSidewaysResult>> facetToDrillSidewaysResultsConverter)
      throws IOException, InvalidQueryException {
    // Ensure that we have an exact count.
    checkState(
        topDocs.totalHits.relation == TotalHits.Relation.EQUAL_TO,
        "FacetsCollector did not provide an exact count");
    var totalCount = topDocs.totalHits.value;
    return switch (collectorQuery.collector()) {
      case FacetCollector facetCollector -> {
        Map<FacetDefinition.Type, Map<String, FacetDefinition>> typeToFacetToDefinition =
            facetCollector.getFacetDefinitionsByType();
        Optional<FieldPath> returnScope = collectorQuery.returnScope().map(ReturnScope::path);
        Map<String, FacetInfo> facets =
            CheckedStream.from(
                    Stream.of(
                            getDrillSidewaysStringFacetResult(
                                searcherReference,
                                typeToFacetToDefinition.get(FacetDefinition.Type.STRING),
                                returnScope,
                                facetToDrillSidewaysResultsConverter),
                            getDrillSidewaysBoundaryFacetResults(
                                typeToFacetToDefinition.get(FacetDefinition.Type.NUMBER),
                                this.facetContext,
                                totalCount,
                                returnScope,
                                facetToDrillSidewaysResultsConverter),
                            getDrillSidewaysBoundaryFacetResults(
                                typeToFacetToDefinition.get(FacetDefinition.Type.DATE),
                                this.facetContext,
                                totalCount,
                                returnScope,
                                facetToDrillSidewaysResultsConverter))
                        .flatMap(map -> map.entrySet().stream()))
                .collectToMapChecked(
                    Map.Entry::getKey,
                    Map.Entry::getValue,
                    (v1, v2) -> {
                      throw new InvalidQueryException(
                          format("Found multiple facets with same name : %s and %s", v1, v2));
                    });

        Optional<Map<String, TermStatsInfo>> termStats = 
            collectTermStats(searcherReference, collectorQuery.termStats());

        yield new MetaResults(
            LuceneFacetResultUtil.getCount(topDocs.totalHits.value, collectorQuery.count().type()),
            Optional.of(facets),
            termStats);
      }
    };
  }

  private Map<String, FacetInfo> getBoundaryFacetResults(
      Map<String, FacetDefinition> facetToDefinition,
      FacetsCollector collector,
      LuceneFacetContext facetContext,
      long totalCount,
      Optional<FieldPath> returnScope)
      throws IOException, InvalidQueryException {
    Map<String, FacetInfo> resultMap = new HashMap<>();
    for (Map.Entry<String, FacetDefinition> entry : facetToDefinition.entrySet()) {
      String key = entry.getKey();
      FacetInfo facetInfo =
          getBoundaryFacetResult(
              entry.getValue(), collector, facetContext, totalCount, returnScope);

      resultMap.put(key, facetInfo);
    }
    return resultMap;
  }

  private FacetInfo getBoundaryFacetResult(
      FacetDefinition facetDefinition,
      DrillSidewaysResult drillSidewaysResult,
      LuceneFacetContext facetContext,
      long totalCount,
      Optional<FieldPath> returnScope)
      throws IOException, InvalidQueryException {
    var boundaryDefinition = (FacetDefinition.BoundaryFacetDefinition<?>) facetDefinition;
    String path = facetContext.getBoundaryFacetPath(boundaryDefinition, returnScope);
    FacetResult facetResult =
        drillSidewaysResult.facets.getTopChildren(boundaryDefinition.boundaries().size() - 1, path);
    List<FacetBucket> results = new ArrayList<>();
    @Var long facetDocsCount = 0;
    for (int i = 0; i < facetResult.labelValues.length; i++) {
      long bucketCount = facetResult.labelValues[i].value.longValue();
      if (bucketCount > 0) {
        facetDocsCount += bucketCount;
        results.add(new FacetBucket(boundaryDefinition.boundaries().get(i), bucketCount));
      }
    }

    if (boundaryDefinition.defaultBucketName().isPresent()) {
      // Default bucket can be computed by subtracting the total docs in the buckets from the
      // total docs returned by the query, which is accurate when provided by the FacetsCollector.
      // This also relies on the fact that we do not index numbers or dates in arrays.
      results.add(
          new FacetBucket(
              new BsonString(boundaryDefinition.defaultBucketName().get()),
              totalCount - facetDocsCount));
    }

    return new FacetInfo(results);
  }

  private FacetInfo getBoundaryFacetResult(
      FacetDefinition facetDefinition,
      FacetsCollector facetsCollector,
      LuceneFacetContext facetContext,
      long totalCount,
      Optional<FieldPath> returnScope)
      throws IOException, InvalidQueryException {
    var boundaryDefinition = (FacetDefinition.BoundaryFacetDefinition<?>) facetDefinition;
    FacetResult facetResult =
        LuceneFacetResultUtil.getBoundaryFacetResult(
            boundaryDefinition, facetContext, facetsCollector, returnScope);
    List<FacetBucket> results = new ArrayList<>();
    @Var long facetDocsCount = 0;
    for (int i = 0; i < facetResult.labelValues.length; i++) {
      long bucketCount = facetResult.labelValues[i].value.longValue();
      facetDocsCount += bucketCount;
      results.add(new FacetBucket(boundaryDefinition.boundaries().get(i), bucketCount));
    }

    if (boundaryDefinition.defaultBucketName().isPresent()) {
      // Default bucket can be computed by subtracting the total docs in the buckets from the
      // total docs returned by the query, which is accurate when provided by the FacetsCollector.
      // This also relies on the fact that we do not index numbers or dates in arrays.
      results.add(
          new FacetBucket(
              new BsonString(boundaryDefinition.defaultBucketName().get()),
              totalCount - facetDocsCount));
    }

    return new FacetInfo(results);
  }

  private Map<String, FacetInfo> getDrillSidewaysStringFacetResult(
      LuceneIndexSearcherReference searcherReference,
      Map<String, FacetDefinition> stringFacetToDefinition,
      Optional<FieldPath> returnScope,
      Function<String, Optional<DrillSidewaysResult>> facetToDrillSidewaysResultsConverter)
      throws IOException, InvalidQueryException {

    var searcher = searcherReference.getIndexSearcher();
    if (stringFacetToDefinition.isEmpty()) {
      return Map.of();
    }
    Map<FieldTypeDefinition.Type, Map<String, FacetDefinition.StringFacetDefinition>>
        facetableStringTypeToNameToDefinition =
            LuceneFacetResultUtil.groupFacetableStringDefinitions(
                this.facetContext, stringFacetToDefinition, returnScope);

    return Stream.of(
            getStringFacetFieldDrillSidewaysResults(
                facetableStringTypeToNameToDefinition.get(FieldTypeDefinition.Type.STRING_FACET),
                facetToDrillSidewaysResultsConverter,
                searcher),
            getTokenFieldDrillSidewaysResults(
                facetableStringTypeToNameToDefinition.get(FieldTypeDefinition.Type.TOKEN),
                returnScope,
                facetToDrillSidewaysResultsConverter,
                searcher))
        .flatMap(map -> map.entrySet().stream())
        .collect(
            Collectors.toMap(
                Map.Entry::getKey,
                Map.Entry::getValue,
                (facetInfo1, facetInfo2) -> {
                  if (!facetInfo1.buckets().isEmpty() && !facetInfo2.buckets().isEmpty()) {
                    throw new IllegalStateException(
                        String.format(
                            "Facet has different facet infos as string and token types - %s and %s",
                            facetInfo1, facetInfo2));
                  }
                  return facetInfo1.buckets().isEmpty() ? facetInfo2 : facetInfo1;
                }));
  }

  private Map<String, FacetInfo> getTokenFieldDrillSidewaysResults(
      Map<String, FacetDefinition.StringFacetDefinition> stringFacetToDefinition,
      Optional<FieldPath> returnScope,
      Function<String, Optional<DrillSidewaysResult>> facetToDrillSidewaysResultsConverter,
      LuceneIndexSearcher searcher)
      throws IOException, InvalidQueryException {

    // Should still report facet categories with a count of 0 if no facets have been indexed.
    if (searcher.getTokenFacetsStateCache().isEmpty()) {
      return CollectionUtils.newMapFromKeys(
          stringFacetToDefinition, (ignored1, ignored2) -> new FacetInfo(List.of()));
    }

    Map<String, FacetInfo> result = new HashMap<>();
    TokenFacetsStateCache facetsState = searcher.getTokenFacetsStateCache().get();
    Optional<FacetFeatureExplainer> explainer = LuceneFacetResultUtil.getFacetFeatureExplainer();
    for (var entry : stringFacetToDefinition.entrySet()) {

      FacetDefinition.StringFacetDefinition facetDefinition = entry.getValue();
      String path = facetDefinition.path();
      String lucenePath =
          FieldName.TypeField.TOKEN.getLuceneFieldName(FieldPath.parse(path), returnScope);
      Optional<TokenSsdvFacetState> fieldState = facetsState.get(lucenePath);
      explainer.ifPresent(
          exp ->
              exp.addTotalStringFacetCardinalities(
                  entry.getKey(), fieldState.map(state -> state.getOrdRange(lucenePath))));

      Optional<DrillSidewaysResult> drillSidewaysResult =
          facetToDrillSidewaysResultsConverter.apply(entry.getKey());
      if (drillSidewaysResult.isEmpty()) {
        result.put(entry.getKey(), new FacetInfo(List.of()));
        continue;
      }
      Facets facetCounts = drillSidewaysResult.get().facets;

      Optional<FacetResult> children =
          Optional.ofNullable(facetCounts.getTopChildren(facetDefinition.numBuckets(), lucenePath));

      // can happen when the dimension was never indexed, hits does not contain facet, etc
      if (children.isEmpty()) {
        result.put(entry.getKey(), new FacetInfo(List.of()));
        continue;
      }
      var buckets =
          Stream.of(children.get().labelValues)
              .map(child -> new FacetBucket(new BsonString(child.label), child.value.longValue()))
              .collect(Collectors.toList());
      result.put(entry.getKey(), new FacetInfo(buckets));
    }

    explainer.ifPresent(
        exp -> exp.addNonIntermediateQueriedStringFacetCardinalities(Map.copyOf(result)));

    return result;
  }

  private Map<String, FacetInfo> getStringFacetFieldDrillSidewaysResults(
      Map<String, FacetDefinition.StringFacetDefinition> stringFacetToDefinition,
      Function<String, Optional<DrillSidewaysResult>> facetToDrillSidewaysResultsConverter,
      LuceneIndexSearcher searcher)
      throws IOException {

    // Should still report facet categories with a count of 0 if no facets have been indexed.
    if (searcher.getFacetsState().isEmpty()) {
      return CollectionUtils.newMapFromKeys(
          stringFacetToDefinition, (ignored1, ignored2) -> new FacetInfo(List.of()));
    }

    Map<String, FacetInfo> result = new HashMap<>();

    var facetsState = searcher.getFacetsState().get();
    Optional<FacetFeatureExplainer> explainer = LuceneFacetResultUtil.getFacetFeatureExplainer();
    for (var entry : stringFacetToDefinition.entrySet()) {
      FacetDefinition.StringFacetDefinition facetDefinition = entry.getValue();
      explainer.ifPresent(
          exp ->
              exp.addTotalStringFacetCardinalities(
                  entry.getKey(),
                  Optional.ofNullable(facetsState.getOrdRange(facetDefinition.path()))));

      String path = facetDefinition.path();

      Optional<DrillSidewaysResult> drillSidewaysResult =
          facetToDrillSidewaysResultsConverter.apply(entry.getKey());
      if (drillSidewaysResult.isEmpty()) {
        result.put(entry.getKey(), new FacetInfo(List.of()));
        continue;
      }
      Facets facetCounts = drillSidewaysResult.get().facets;

      Optional<FacetResult> children =
          Optional.ofNullable(facetCounts.getTopChildren(facetDefinition.numBuckets(), path));

      // can happen when the dimension was never indexed, hits does not contain facet, etc
      if (children.isEmpty()) {
        result.put(entry.getKey(), new FacetInfo(List.of()));
        continue;
      }
      var buckets =
          Stream.of(children.get().labelValues)
              .map(child -> new FacetBucket(new BsonString(child.label), child.value.longValue()))
              .collect(Collectors.toList());
      result.put(entry.getKey(), new FacetInfo(buckets));
    }

    explainer.ifPresent(
        exp -> exp.addNonIntermediateQueriedStringFacetCardinalities(Map.copyOf(result)));

    return result;
  }

  private Map<String, FacetInfo> getDrillSidewaysBoundaryFacetResults(
      Map<String, FacetDefinition> facetToDefinition,
      LuceneFacetContext facetContext,
      long totalCount,
      Optional<FieldPath> returnScope,
      Function<String, Optional<DrillSidewaysResult>> facetToDrillSidewaysResultsConverter)
      throws IOException, InvalidQueryException {
    return CheckedStream.from(
            facetToDefinition.entrySet().stream()
                .filter(
                    entry ->
                        facetToDrillSidewaysResultsConverter.apply(entry.getKey()).isPresent()))
        .<String, FacetInfo, RuntimeException, IOException, InvalidQueryException>
            collectToMapCheckedBiValueException(
                Map.Entry::getKey,
                entry ->
                    getBoundaryFacetResult(
                        entry.getValue(),
                        facetToDrillSidewaysResultsConverter.apply(entry.getKey()).get(),
                        facetContext,
                        totalCount,
                        returnScope));
  }

  private Map<String, FacetInfo> getStringFacetResult(
      LuceneIndexSearcherReference searcherReference,
      Map<String, FacetDefinition> stringFacetDefinitions, // Keyed by facet name.
      FacetsCollector collector,
      Optional<FieldPath> returnScope,
      boolean concurrentQuery)
      throws IOException, InterruptedException, InvalidQueryException {

    var searcher = searcherReference.getIndexSearcher();

    if (stringFacetDefinitions.isEmpty()) {
      return Map.of();
    }
    Optional<FacetFeatureExplainer> explainer = LuceneFacetResultUtil.getFacetFeatureExplainer();

    Map<FieldTypeDefinition.Type, Map<String, FacetDefinition.StringFacetDefinition>>
        facetableStringTypeToNameToDefinition =
            LuceneFacetResultUtil.groupFacetableStringDefinitions(
                this.facetContext, stringFacetDefinitions, returnScope);

    var stringFacetFieldResults =
        getStringFacetFieldResult(
            explainer,
            facetableStringTypeToNameToDefinition.get(FieldTypeDefinition.Type.STRING_FACET),
            searcher,
            collector,
            concurrentQuery);
    var tokenFieldResults =
        getTokenFieldResult(
            explainer,
            facetableStringTypeToNameToDefinition.get(FieldTypeDefinition.Type.TOKEN),
            searcher,
            collector,
            returnScope,
            concurrentQuery);
    var result = new HashMap<>(stringFacetFieldResults);
    result.putAll(tokenFieldResults);
    return result;
  }

  private Map<String, FacetInfo> getStringFacetFieldResult(
      Optional<FacetFeatureExplainer> facetFeatureExplainer,
      Map<String, FacetDefinition.StringFacetDefinition> stringFacetToDefinition,
      LuceneIndexSearcher searcher,
      FacetsCollector collector,
      boolean concurrentQuery)
      throws IOException, InterruptedException {

    var result = new HashMap<String, FacetInfo>();
    Optional<ExplainTimings> facetTimings =
        facetFeatureExplainer.map(FacetFeatureExplainer::getCreateCountTimings);

    // Should still report facet categories with a count of 0 if no facets have been indexed.
    if (searcher.getFacetsState().isEmpty()) {
      return CollectionUtils.newMapFromKeys(
          stringFacetToDefinition, (k, v) -> new FacetInfo(List.of()));
    }
    var facetsState = searcher.getFacetsState().get();
    Facets counts;
    try (var unused =
        new InvocationCountingTimer.AutocloseableOptional<>(
            facetTimings.map(t -> t.split(ExplainTimings.Type.GENERATE_FACET_COUNTS)))) {
      counts =
          concurrentQuery && this.concurrentSearchExecutor.isPresent()
              ? new ConcurrentSortedSetDocValuesFacetCounts(
                  facetsState, collector, this.concurrentSearchExecutor.get())
              : new SortedSetDocValuesFacetCounts(facetsState, collector);
    }

    for (var entry : stringFacetToDefinition.entrySet()) {
      facetFeatureExplainer.ifPresent(
          explainer ->
              explainer.addTotalStringFacetCardinalities(
                  entry.getKey(),
                  Optional.ofNullable(facetsState.getOrdRange(entry.getValue().path()))));
      populateFacetBuckets(
          counts, entry.getKey(), entry.getValue().path(), entry.getValue().numBuckets(), result);
    }

    facetFeatureExplainer.ifPresent(
        explainer ->
            explainer.addNonIntermediateQueriedStringFacetCardinalities(Map.copyOf(result)));

    return result;
  }

  private Map<String, FacetInfo> getTokenFieldResult(
      Optional<FacetFeatureExplainer> facetFeatureExplainer,
      Map<String, FacetDefinition.StringFacetDefinition> stringFacetToDefinition,
      LuceneIndexSearcher searcher,
      FacetsCollector collector,
      Optional<FieldPath> returnScope,
      boolean concurrentQuery)
      throws IOException, InterruptedException, InvalidQueryException {
    var result = new HashMap<String, FacetInfo>();
    Optional<ExplainTimings> facetTimings =
        facetFeatureExplainer.map(FacetFeatureExplainer::getCreateCountTimings);

    if (stringFacetToDefinition.isEmpty()) {
      return Map.of();
    }
    // If cache optional is empty, then FF enabling token facets is not enabled
    if (searcher.getTokenFacetsStateCache().isEmpty()) {
      throw new InvalidQueryException(
          format(
              "Faceting over token fields is not enabled. Facets %s are indexed as tokens."
                  + " Please remove them from this query, or index the fields as stringFacet",
              stringFacetToDefinition.keySet()));
    }

    var tokenFacetsStateCache = searcher.getTokenFacetsStateCache().get();

    for (var entry : stringFacetToDefinition.entrySet()) {
      var lucenePath =
          FieldName.TypeField.TOKEN.getLuceneFieldName(
              FieldPath.parse(entry.getValue().path()), returnScope);
      var fieldState = tokenFacetsStateCache.get(lucenePath);
      facetFeatureExplainer.ifPresent(
          explainer ->
              explainer.addTotalStringFacetCardinalities(
                  entry.getKey(), fieldState.map(state -> state.getOrdRange(lucenePath))));

      if (fieldState.isEmpty()) {
        result.put(entry.getKey(), new FacetInfo(List.of()));
        continue;
      }
      Facets counts;
      try (var unused =
          new InvocationCountingTimer.AutocloseableOptional<>(
              facetTimings.map(t -> t.split(ExplainTimings.Type.GENERATE_FACET_COUNTS)))) {
        counts =
            concurrentQuery && this.concurrentSearchExecutor.isPresent()
                ? new com.xgen.mongot.index.lucene.facet.ConcurrentSortedSetDocValuesFacetCounts(
                    fieldState.get(), collector, this.concurrentSearchExecutor.get())
                : new com.xgen.mongot.index.lucene.facet.SortedSetDocValuesFacetCounts(
                    fieldState.get(), collector);
      }
      FacetDefinition.StringFacetDefinition definition = entry.getValue();
      populateFacetBuckets(counts, entry.getKey(), lucenePath, definition.numBuckets(), result);
    }

    facetFeatureExplainer.ifPresent(
        explainer ->
            explainer.addNonIntermediateQueriedStringFacetCardinalities(Map.copyOf(result)));

    return result;
  }

  private void populateFacetBuckets(
      Facets counts, String facetName, String path, int numBuckets, Map<String, FacetInfo> result)
      throws IOException {
    FacetResult children = counts.getTopChildren(numBuckets, path);
    // can happen when the dimension was never indexed, hits does not contain facet, etc
    if (children == null) {
      result.put(facetName, new FacetInfo(List.of()));
      return;
    }
    var buckets =
        Stream.of(children.labelValues)
            .filter(child -> child.label != null && !child.label.isEmpty())
            .map(child -> new FacetBucket(new BsonString(child.label), child.value.longValue()))
            .collect(Collectors.toList());
    result.put(facetName, new FacetInfo(buckets));
  }

  /**
   * Collects term statistics for the requested fields.
   * Only text-indexed fields (TOKEN, STRING, AUTOCOMPLETE) support term statistics.
   * Numeric, date, and vector fields are skipped as they don't have traditional term dictionaries.
   *
   * @param searcherReference Reference to the Lucene index searcher
   * @param termStatsRequest The term statistics request containing field names
   * @return Map of field names to their term statistics
   */
  public Optional<Map<String, TermStatsInfo>> collectTermStats(
      LuceneIndexSearcherReference searcherReference,
      Optional<TermStatsRequest> termStatsRequest)
      throws IOException {
    if (termStatsRequest.isEmpty()) {
      return Optional.empty();
    }

    IndexReader reader = searcherReference.getIndexSearcher().getIndexReader();
    Map<String, TermStatsInfo> termStats = new HashMap<>();

    for (String userFieldName : termStatsRequest.get().definition().fields()) {
      // Find all Lucene fields that match this user field name
      // User specifies "title", but Lucene stores "$type:string/title", "$type:token/title", etc.
      List<String> matchingLuceneFields = findMatchingLuceneFields(reader, userFieldName);
      
      if (matchingLuceneFields.isEmpty()) {
        // Field doesn't exist or has no terms, return zeros
        termStats.put(userFieldName, new TermStatsInfo(0, 0, 0, 0, 0.0));
        continue;
      }
      
      // Validate that at least one matching field is text-indexed
      // Only TOKEN, STRING, and AUTOCOMPLETE fields have traditional term dictionaries
      List<String> textIndexedFields = matchingLuceneFields.stream()
          .filter(this::isTextIndexedField)
          .collect(Collectors.toList());
      
      if (textIndexedFields.isEmpty()) {
        // Field exists but is not text-indexed (e.g., numeric, date, vector fields)
        // Return zeros to indicate no term statistics are available
        termStats.put(userFieldName, new TermStatsInfo(0, 0, 0, 0, 0.0));
        continue;
      }

      // Aggregate statistics across all text-indexed Lucene field types
      @Var long totalSumDocFreq = 0;
      @Var long totalSumTotalTermFreq = 0;
      @Var int maxDocCount = 0;
      @Var long totalSize = 0;

      for (String luceneFieldName : textIndexedFields) {
        Terms terms = MultiTerms.getTerms(reader, luceneFieldName);
        if (terms != null) {
          long sumDocFreq = terms.getSumDocFreq();
          long sumTotalTermFreq = terms.getSumTotalTermFreq();
          int docCount = terms.getDocCount();
          @Var long size = terms.size();
          
          // If size() returns -1 (unavailable), fall back to 0
          // This happens for some field types where term count isn't tracked
          if (size < 0) {
            size = 0;
          }

          totalSumDocFreq += sumDocFreq;
          totalSumTotalTermFreq += sumTotalTermFreq;
          totalSize += size;
          
          // docCount is the number of documents with this field
          // Use the maximum across all type fields for the same user field
          if (docCount > maxDocCount) {
            maxDocCount = docCount;
          }
        }
      }
      
      // totalDocFreq represents the number of unique terms
      long totalDocFreq = totalSize;

      // Calculate average document frequency per term
      double avgDocFreq = totalSize > 0 ? (double) totalSumDocFreq / totalSize : 0.0;

      termStats.put(
          userFieldName,
          new TermStatsInfo(totalDocFreq, totalSumDocFreq, totalSumTotalTermFreq, maxDocCount, avgDocFreq));
    }

    return Optional.of(termStats);
  }

  /**
   * Finds all Lucene field names that correspond to a user-specified field name.
   * For example, "title" might map to "$type:string/title", "$type:token/title", etc.
   */
  private List<String> findMatchingLuceneFields(IndexReader reader, String userFieldName) {
    FieldPath fieldPath = FieldPath.parse(userFieldName);
    FieldInfos fieldInfos = FieldInfos.getMergedFieldInfos(reader);
    
    List<String> matchingFields = new ArrayList<>();
    for (FieldInfo fieldInfo : fieldInfos) {
      String luceneFieldName = fieldInfo.name;
      
      // Check if this Lucene field matches the user's field name
      try {
        // Skip meta fields and static fields
        if (FieldName.MetaField.isMetaField(luceneFieldName) ||
            isStaticField(luceneFieldName)) {
          continue;
        }
        
        // Extract the field path from the Lucene field name
        FieldPath luceneFieldPath = FieldName.getFieldPath(luceneFieldName);
        
        // If the field paths match, this Lucene field is for the user's field
        if (luceneFieldPath.equals(fieldPath)) {
          matchingFields.add(luceneFieldName);
        }
      } catch (IllegalArgumentException e) {
        // Skip fields that can't be parsed
        continue;
      }
    }
    
    return matchingFields;
  }

  private boolean isStaticField(String fieldName) {
    for (FieldName.StaticField staticField : FieldName.StaticField.values()) {
      if (staticField.isTypeOf(fieldName)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Checks if a Lucene field name represents a text-indexed field that has term statistics.
   * Only TOKEN, STRING, and AUTOCOMPLETE fields have traditional inverted indexes with term dictionaries.
   * Numeric, date, and vector fields use point trees or other structures without term statistics.
   *
   * @param luceneFieldName The Lucene field name (e.g., "$type:token/title")
   * @return true if the field is text-indexed, false otherwise
   */
  private boolean isTextIndexedField(String luceneFieldName) {
    return FieldName.TypeField.TOKEN.isTypeOf(luceneFieldName)
        || FieldName.TypeField.STRING.isTypeOf(luceneFieldName)
        || FieldName.TypeField.AUTOCOMPLETE.isTypeOf(luceneFieldName);
  }
}

